### PR TITLE
Translations for Portuguese 

### PR DESCRIPTION
**Pull request by alexcvcoelho**
I translated files for Portuguese with format of release 2.5.4. 
I have added the follow line:
```javascript
locale = locale == "pt-BR" ? "br" : locale;
```
[Here](https://github.com/LaCasemate/fab-manager/compare/dev...alexcvcoelho:master#diff-60787af36564243f2d0a86430c9100c1)  because in application.yml the variable MESSAGEFORMAT_LOCALE don't pass to messageformat any value, just insert the correct file js in html. And for portuguese tranlation, rails_locale and app_locale need have value "pt-BR", and the messageformat needs be "br". 
Can anyone help me whit this?

Thanks.

### CODE REVIEW

**Comment by sylvainbx** [comment]
Hi @alexcvcoelho , many thanks for your contribution.
Concerning messageformat, this sounds like a bug. I will check that asap and keep you updated.

**Comment by sylvainbx** [comment]
Ok, I've looked over the code and, the locale you're overriding in messageformat is set by APP_LOCALE. 

So the behavior you see is normal. Now the question is: do you really need to localize your app translation files ? 

For exemple, can't `app.logged.pt-BR.yml` be renamed `app.logged.pt.yml` ?
I don't know anything about Portuguese, so you're the only one able to judge, if there's some critical differences between PT and PT-BR in thoses files (app.admin, app.logged, app.public and app.shared).

Please, can you tell me more about this ?

**Comment by alexcvcoelho** [comment]
Sorry for delay. But I really need  use pt-BR, there aren't a big difference between pt-BR and pt but for Brazilians is strange use a software with Portugal language, but we have a option to use pt temporary until anyone portuguese from Portugal need use a locations file, what do you thing?

**Comment by sylvainbx** [comment]
Hi @alexcvcoelho ,
First i would remove your modifications in `angular-translate-interpolation-messageformat.js`, because this is not safe in case of library upgrade.
To overcome the problem your facing, without this hack, I suggest to rename your `app.*.pt-BR.yml` files to `app.*.pt.yml`. This way, you'll be able to configure `APP_LOCALE : 'pt'`and let the other variables set to `pt-BR`, especially `RAILS_LOCALE`.
This should do the trick :) Please, can you test and report here your feedback ?

**Comment by alexcvcoelho** [comment]
Thanks @sylvainbx, that's ok. I changed the name of files `pt-BR` to `pt` and for configure application to brasilian portuguese need to use in `config/applicatiom.yml` following params:

```yml
RAILS_LOCALE: 'pt-BR'
APP_LOCALE: 'pt'
MOMENT_LOCALE: 'pt-br'
SUMMERNOTE_LOCALE: 'pt-BR'
ANGULAR_LOCALE: 'pt-br'
MESSAGEFORMAT_LOCALE: 'pt'
FULLCALENDAR_LOCALE: 'pt-br'

ELASTICSEARCH_LANGUAGE_ANALYZER: 'brasilia'

TIME_ZONE: 'Brasilia'
WEEK_STARTING_DAY: 'monday'
D3_DATE_FORMAT: '%d/%m/%y'
UIB_DATE_FORMAT: 'dd/MM/yyyy'
EXCEL_DATE_FORMAT: 'dd/mm/yyyy'
```

**Comment by sylvainbx** [comment]
That looks great! I'll review it on monday or tuesday and keep you updated. Thanks!

**Comment by sylvainbx** [comment]
Hi @alexcvcoelho , I've just merged your translations into the [dev branch](https://github.com/LaCasemate/fab-manager/tree/dev). You've made an amazing work translating everything, thank you very much.
FWI, there was only a new translation added in the meantime and few messageFormat typo, [I fixed here](https://github.com/LaCasemate/fab-manager/commit/3bf91efe8f22e84fd4053ca0b6e68159aec8fff8).

You changes will be published with the next release (2.5.7 I guess). 
Thanks again for your work, and do not hesitate to give me your feedback about the translation process, if there's anything to improve ...

**Pull request merged**
