### PR TITLE
Added reservation deadlines for each type of reservation

### PR DESCRIPTION
**Pull request by Guichaguri**
This PR is an improvement of #414, which adds deadlines for each type of reservation. Now there's an option to set the deadline for specifically for machines, trainings, events or spaces.

This allows fine tuning the deadline. Our FabLab can allow reservation of a space a few minutes prior, but a training needs at least a day prior.

Thank you!

### CODE REVIEW

**Comment by Guichaguri** [comment]
The tests only cover spaces. As the logic is the same for the other types of reservations, do you think we also need tests for them?

**Comment by sylvainbx** [comment]
Hi @Guichaguri ,
Thanks for you contribution. The code seems ok to me, I'll give a try and merge it for the next feature release.

**Comment by sylvainbx** [comment]
Hi @Guichaguri , I just made some changes that conflict with yours. Would you mind rebasing your work on the lastest commits on [dev](https://github.com/sleede/fab-manager/tree/dev), please?

**Comment by Guichaguri** [comment]
@sylvainbx Done!

**Comment by sylvainbx** [comment]
I just merged you branch and I will publish the new release very soon. You may want to provide [the Portuguese translations](https://translate.fab-manager.com/project/fab-manager/pt-PT)?

**Pull request merged**
