### PR TITLE
Update and corrections of docker installation instructions and environment variables

### PR DESCRIPTION
**Pull request by enomarin**
- Update of doc/postgresql_readme.md to correspond to the default database name
- Removing some space in env.example
- Update of the letsencrypt v2 URL in docker/webroot.ini.example

### CODE REVIEW

**Comment by sylvainbx** [comment]
Hi @enomarin and thanks for your contribution.
I've rebased your changes to the `dev` branch which contains the last commits but it created some conflits. Can you take a look at this?

**Comment by enomarin** [comment]
Hi @sylvainbx it seem that you don't need the let's encrypt url in webroot.ini.example after your update of the setup scripts ?
I made a merge of my changes with the last version of `sleede/fab-manager`dev branch on my fork.
Do I make another pull request ?

Strangely, I didn't had conflicts with the env.example file, all went fine.

ps : I still have questions about the postgresql readme, I made a script to automate the dumping of the database on a NAS which don't use this method.

**Comment by sylvainbx** [comment]
Yes: we already have updated the let's encrypt procedure to use the new url!

I don't think you need to open another pull request, just `git push` to your github account on branch dev (click on "view command line instructions" below).

Can you share your dumping script? If your procedure is easier than the current, we can replace it in the documentation

**Comment by enomarin** [comment]
I've already pushed my modifications on `enomarin/fab-manager` but I've don't have the write access on sleede/fab-manager.
When I try to make a pull request with the new update it seem that github can automatically merge the two branches.
After looking at my script (I've writted it a month ago), it seem that it's the same  aside the fact that I didn't enter into the container in order to continue the script's execution.

I think i was more intrigued about the commands to restore the dump, especially about the utility of the `rake db:drop` and `rake db:create` commands.

Also I think the line: `sudo cp fablab_production_$(date -I).sql .docker/postgresql/` should look somethink like `sudo cp fablab_production_$(date -I).sql postgresql/` with a `cd /apps/fabmanager/` before.

What do you think of that ?

**Comment by enomarin** [comment]
I've advanced  on automating the dumping and restoration of the Postgresql database with bash scripts.

The scripts looks like this:
```
#!/bin/bash
cd /apps/fabmanager/
docker-compose exec postgres pg_dump -F t -U postgres fablab_production.sql
```
We need to dump the database as a tar (-F t option) to make it possible to restore it with the pg_restore command.

To restore the database:
```
#!/bin/bash
cd /apps/fabmanager/
docker-compose restart
docker-compose exec postgres dropdb -U postgres fablab_production
docker-compose exec postgres createdb -U postgres fablab_production
docker-compose exec postgres pg_restore -U postgres -d fablab_production --clean /var/lib/postgresql/data/fablab_production.sql
```
Restarting the docker container is the only way I find to disconnect the clients of the database, otherwise it was not possible to drop the database.
I'm open to other suggestions !
There are two other improvement which could be made:
- Rempacing the dropdb and createdb by recreating the database with pg_restore and some options (the tests that I've made wasn't effective).
- Upgrade the docker-compose api which would permits to specify the root folder of execution of the bash command.

I've haven't made extensive testing of these scripts but it work with a manual drop of the database.

**Comment by sylvainbx** [comment]
Hi @enomarin, sorry for the delay... 
`rake db:drop` and `rake db:create` handle the database deletion and re-creation. It seems to my eyes, to be mostly the same as:

    docker-compose exec postgres dropdb -U postgres fablab_production
    docker-compose exec postgres createdb -U postgres fablab_production

Meanwhile, i would proceed differently: first shut down the instance to prevent conflits during the operation (`docker-compose down`, instead of `restart`) then use `docker-compose run xxx` for each commands, instead of `docker-compose exec xxx`.

If you say that dumping and restoring operations are working correctly... then I'll trust you :)

**Comment by enomarin** [comment]
@sylvainbx No problem for the delay, you must be very busy with the maintenance of fabmanager.

Yeah, I made some research and the answer wasn't difficult to find.
At contrary, I (and `rake`) haven't found the rakefile containing the commands.
If I find it, or create it, I could integrate my scripts and make (another) pull request !

Your right ! Using `run` is a better idea than `exec` in this case, my script was pretty brutal with the containers.

I put an option on the database's restoring script because it seem to make some duplicate of accounts. Beside that, it may be a silly question, but I've haven't found how to delete an account from the admin panel.

**Comment by sylvainbx** [comment]
The rake tasks must be launched from the app container, eg:

    docker-compose run --rm fabmanager bundle exec rake db:drop

It seems very strange to my eyes that it creates duplicated accounts! maybe this is related to the non-shutdown of the application... It would be nice if you can test it ;)

And you question is not silly at all: there is no way to delete a member's account from the admin panel in the last release. This is only available in the dev branch for the moment and will be released in the next upcoming weeks ;)


Just noticed: if you can't update this pull request, maybe this is due to my rebase on the `dev` branch. So maybe you have to push your changes to another branch in your repository?

**Comment by enomarin** [comment]
It seem pretty logical afterall, I'm new to all the stack of fabmanager :)

The rakefile isn't the one at the root of the `sleede/fabmanager`'s repo, isn't it ?

It is possible to remove the accounts from the admin panel ?
It would ease my testing of the database backup scripts !

**Comment by sylvainbx** [comment]
In development environments, just `git checkout dev` and you'll be able to remove accounts from the UI. In production, replace `image: sleede/fab-manager` by `image: sleede/fab-manager:dev` in your docker-compose.yml, then `docker-compose pull`, `... down` and `... up -d` will do the trick.

In any cases, I advise you to read the [changelog](https://github.com/sleede/fab-manager/blob/dev/CHANGELOG.md) for commands to run (like rake db:migrate).

The rake file is the one you said. It's the entry point for `rake` which is a ruby-on-rails built-in utility to launch ruby scripts.

**Comment by enomarin** [comment]
@sylvainbx thank you for these informations
I've pull the dev container, I've got some extra features like importing members but I can't see where I could delete the members.

These new features made me think about a thing: would it be easy to implement a feature to import calendar as you can do it with members ?
## Updates
Using the `run` command instead of  `exec` for the `dropdb`  command of the postgres container throw an `could not connect to database` error.
I find a compromise by running `docker-compose down` and just relaunching the postgres container. After a `dropdb` and a `pg_restore` with a `--create` option I simply do a `docker-compose up -d`.

The script (tested and aproved) look like this : 
```
#!/bin/bash
# Restore the sql database in /apps/fabmanager/postgresql/fablab_production.sql

cd /apps/fabmanager/
docker-compose down
docker-compose up -d postgres
docker-compose exec postgres dropdb -U postgres fablab_production
docker-compose exec postgres createdb -U postgres fablab_production
docker-compose exec postgres pg_restore -U postgres -d fablab_production /var/lib/postgresql/data/fablab_production.sql
docker-compose up -d
```

**Comment by sylvainbx** [comment]
You should have some delete buttons in the users list, like this:
image

About importing some calendars, it's already done in dev, you could try in [manage the calendar] > [⇄] (at the top right of the screen). Feedbacks welcome :)

---
Strange about the error you are reporting. But the script you are reporting seems OK for me. So if you can't update your pull request, would you mind about opening a new one?

**Comment by sylvainbx** [comment]
Hi @enomarin 
I've changed the instruction to restore the dump, according to your script (see the commit above). You can check it at [doc/postgresql_readme.md](https://github.com/sleede/fab-manager/blob/master/doc/postgresql_readme.md#dumping-the-database). I'll close this PR but please do not hesitate to open a new one or reopen and tag me if you think I've missed something.
Thanks again for your contribution

**Comment by enomarin** [comment]
Sorry for the absence...
What a day to return working on fabmanager, all the upgrades I wish for are there !
Thank you :)

Strangely - or not - I couldn't add an event in the calendar without adding the new environment variables.
It may be a good thing to add them in the example env in the container !

I've also had an issue when trying to remove all the recurrence of an event, it throw a `syntax error` in the development tools when I validate the deletion and doesn't show it without refreshing the page.

**Pull request closed without merging**
