### PR TITLE
(feature) allow users to disable colorize_logging in active record

### LINKED ISSUE #345: no option is provided to disable ANSI color escape code
**Describe the bug**

in rails 5.x, `config.colorize_logging` is `true` by default. users cannot disable ANSI color escape code in the log.

**To Reproduce**

1. run `rails db:seed`
2. See the log

**Expected behavior**

There should be an option to disable color in the log.

**Screenshots**

N/A

**Server (please complete the following information):**
 - OS: FreeBSD 13.0
 - Kernel: FreeBSD 14.0-CURRENT amd64
 - Fab-manager version 5.3.13

**Browser (please complete the following information):**
 - Name: N/A
 - Version: N/A
 
**Additional context**

as an admin, i would like to log to file or syslog. logs in color does not look nice in this context. see an example in color at https://github.com/trombik/ansible-role-fab_manager/runs/6353345075?check_suite_focus=true

### PR DESCRIPTION
**Pull request by trombik**
fixes #345

### CODE REVIEW

**Comment by nflorentin** [comment]
hi @trombik and thank you for your help on that !

I would like the name of the env variable to be a little more explicit, what about "COLORIZE_LOGGING_TURNED_OFF" ?

**Comment by trombik** [comment]
`NO_COLOR` was chosen because I agree with this:

https://no-color.org/

it is often bit difficult to disable colour output because its googlability of it is low (it took sometime for me to reach out to the rails option).

**Comment by nflorentin** [comment]
oh, I see !

@sylvainbx any opinion on that ?

**Comment by sylvainbx** [comment]
It makes sense to me. However, I think you must document the new variable in [environment.md](https://github.com/sleede/fab-manager/blob/master/doc/environment.md) for this PR to be accepted.

**Comment by trombik** [comment]
@sylvainbx thanks for the comment. fixed and rebased.

**Pull request merged**
