### PR TITLE
EVENTS: open api and monitor improvement

### PR DESCRIPTION
**Pull request by siteswapjuggler**
Hello there,

I started to test some improvement on the open api and general purpose ergonomy. Here is my first request with those events open api improvement.

CHANGES
new data available: start_at, end_at, event_image
new controllers: id, upcoming, limit

TODO
the doc needs to be updated with new exemple from a real database (mine are mockups)

### CODE REVIEW

**Comment by siteswapjuggler** [comment]
Second request for some events monitor improvement.

CHANGES
Event monitor now prompt reservations so we can have an instant view over reservations
Event monitor filters have been reordered, upcoming event is the default one and now goes chronological
Event monitor have better dates prompt management
Disable Mousewheel in event edit form (no more error possible when you scroll down the page while editing)
-1 free space used to signify a cancelled event (to be prompt in the public modules later)

**Review by nflorentin — CHANGES_REQUESTED** [review]
- What is the purpose of the parameter limit as we already have the parameter page and per_page ?
- there is a double slash in image urls
- param upcoming is ok to me 👍 

Thanks for your contribution

**Comment by siteswapjuggler** [comment]
* the limit parameter offer another way to deal with the number of events, seems more modular to me and more natural in some ways, keeping both option doesn't cost a lot of ressources and offer two interesting way to work for the Open API. Actually I mimicked the way it's done fore other API module wich have both.
* I'll check the double slash issue, there is the same issue in the rss feed but it doesn't cause any trouble for the client the double slash is seen as a simple one by the browsers.
* tanks for upcoming

**Comment by sylvainbx** [comment]
Hi @siteswapjuggler,

First, thank you for contributing to fab-manager, investing your time to share your improvements with the community is very nice.

Meanwhile, you should consider asking us before modifying some behaviors like what you did on the events page. Indeed, we cannot accept your changes concerning the reordering of the events because this was an initial requirement from La Casemate, and moreover it introduces an issue when clicking on "load more projects" : it breaks the "load at bottom" logic. 
The current behavior is to display all events in anti-chronological order for admins and to display events in normal chronological order for non-connected and normal users, hiding them the passed events. This is managed and paginated in the ruby on rails controller.

Concerning the quick view of the number of reservations, this is as great as the way you reorganized the dates and the display. :+1:  Can you provide English and Portuguese translations for this? Disabling mousewheel in the date inputs was a good idea too!

If you can provide the requested changes in the next days, we will wait to include them in the next release to come (2.5.11). Thanks to keep us updated and thank you again for your contribution.

**Comment by siteswapjuggler** [comment]
Hi @sylvainbx ,

thanks for this complete answer. To be honnest I was actually testing stuff to improve my Ruby/Coffee abilities and helping our daily usage of FabManager wich is now spread far beyond the initial commitment of La Casemate and the Inmédiat Centers. Anyway I totally agree with you about you to be the final judge about the needs and direction of the main branch of this project.

I work on the project during my free time, so I'll not work again on it before satursday (or Friday evening at best). I sure can provide English translations but don't know anywords in Portuguese, I still can add the items in the Portuguese file to keep a trace for further translators.

I understand your meaning about the "default" behavior meanwhile it really depends on how people use the app. Ideally I would vote for a system that keeps memory of each admin filters but I'm not skilled enough to do that. The intention is to offer admin a one click way to access the informations they need about events. The current behaviour should have been perfect for the initial requirement but I know it's a real daily pain for us so I feel it need a way to adapt to the most common usages. Without the require to change the default behavior anyway as I understand it will not be conveniant for those who have habits.

Usage example which make us test this new filter : 

A current usage for us will be to have 20 to 40 events from september to june in Fabmanager.  So if I want to know what happen next week I need to go to the bottom of the page, load new event 2 or 3 times then mentally reverse the list to keep track of my priorities. It's not very fluid...

Another example is the two different displays for public and admin (anti-chronological and chronological) that creates a cognitive bias when you cross talk with the public. I mean even in the public module what the admin sees is not what the public sees which create confusion like "look at the first item in the first row, oh no wait for you it should be the fourth row blablabla..."

So here is my todo list purposal : 
* translation in English and Portuguse
* go back to current behavior and adding a fourth filter option so I can choose to see the event in chronological order if we want to in the admin monitor
* come back later for further constructive discussion about ergonomy and other improvement if you're pleased to do so

To keep you in track of my intentions I'd like to focus on the events for now and I have start written a roadmap of what I want to test. I'll be pleased to cross this information with you so we can all contribute in the better way to this project.

Sincerely
Sylvain

**Comment by sylvainbx** [comment]
Hi @siteswapjuggler,

There's no urgent deadline concerning the next release ... we can wait for next week, it's not a problem. Concerning the translations, I don't know anything about Portuguese myself, but maybe @alexcvcoelho can help ... 

About the events list behavior, I understand your problem. You can implement the solution the way you told, or here's my proposal: It will be nice if the admin is able to choose the display order directly from the interface, using a second filter like this:

maquette_fab-manager-events-admin

This filter would have to act in coordination with the other filter (all/passed/events to come) to change the way the controller send the events to the web-app, considering that the default behavior is kept as the current behavior.

Hoping forward to discuss your roadmad,
Regards,
Sylvain :-)

**Comment by sylvainbx** [comment]
We had an urgent bugfix to release for a fablab so we released 2.5.11 today ... Your changes will be included in the next version (2.5.12 probably), sorry for that change

**Comment by siteswapjuggler** [comment]
No problem, I'll test the implementation of your solution by then :)

**Comment by alexcvcoelho** [comment]
Hi @siteswapjuggler 

If it's possible, write the new lines in pt files, in English anyway, and when I have time I translate the files. It's been a long time that I don't translate anything in Fabmanager, but as soon as possible I'll translate.

Thanks.

**Comment by siteswapjuggler** [comment]
Hello there,

@nflorentin : requested changes done
@alexcvcoelho : new lines added in pt files with a #translation_missing comment for you to find easily
@sylvainbx : I implemented a one menu fourth choice option (two click to the sort vs four click with two menus), I also thought about implementing a column sorting as in other admin modules but didn't get it work for now (and still 3 click at least to the sort)

Hope I'll be ok for you and that we could implement this as soon as you'll review the change. We start to implement some client application with the Open API and we need the JSON update to go further.

Next step for me is to share my intended roadmap with you. Do you think of a better tool for me to share with you ?

**Comment by matbgn** [comment]
I guess here could be a good way for sure ; )

**Comment by matbgn** [comment]
I'm making some lobbying :-P but the ability for recursive events on calendar will be a great challenge. What do you think ?

**Comment by sylvainbx** [comment]
Hi @siteswapjuggler,

Thanks for your modifications. I've spoken with @nflorentin and he's ok with the open API changes.

Concerning the events list, I have an issue but I don't think this is your fault ... I thought that the current filters were sorting the events at server-side (in the rails controller) but, reviewing your code, I now understand that this is not the case ... So your implementation follow the existing logic (which is normal) but the existing logic is broken: If you have more than 20 events in your database, the pagination doesn't work correctly for filters other than the default one.

My suggestion is that I'm gonna make the changes to fix it in the [dev](https://github.com/LaCasemate/fab-manager/tree/dev) branch. I'll notify you when it's done and you'll be able to rebase/merge your existing branch onto dev. Do you agree with that ?

Concerning your roadmap, maybe you can open an issue on github explaining what you intend to change. We'll talk about that there ;-)

Thanks again for your contribution !

**Comment by sylvainbx** [comment]
Ok, this is fixed on [dev](https://github.com/LaCasemate/fab-manager/tree/dev), by commit https://github.com/LaCasemate/fab-manager/commit/f874748f74571f452c8633e54413cf46943829f3.
Can you, please, rebase your pull request on [dev](https://github.com/LaCasemate/fab-manager/tree/dev) ([instructions here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#how-do-i-rebase)).

**Comment by siteswapjuggler** [comment]
Lot of work for the science fest I'll go back to this after the rush :)

**Comment by siteswapjuggler** [comment]
@sylvainbx sorry for this long delay, rebasing to dev branch should be ok. Git is quiet strange when you don't pratice it so often. Tell me if it's ok from your side.

Having a better understanding of git will sure be me one of my next move. Before going further on my roadmap on this project.

**Comment by sylvainbx** [comment]
Hi @siteswapjuggler, I'm sorry but I can't see your rebase anywhere ... Do you have pushed it on github?
If you can't manage to rebase, it's ok for me if you simply merge dev on your branch but you may have to solve some conflicts...

**Comment by sylvainbx** [comment]
Hi @siteswapjuggler, I've just merged your pull-request into [dev](https://github.com/LaCasemate/fab-manager/tree/dev) in commit https://github.com/LaCasemate/fab-manager/commit/12c6cd2a7006b54484a388ad7bc625b57a14297c. I'll close this PR as this is resolved for me. 
I was a little bit fuzzy with merge conflicts so can you check it out (dev branch) and verify that everything is OK, according to your specs? This would help me a lot! Please do not hesitate to open a new PR, forked form an up-to-date dev branch, is needed.

**Pull request closed without merging**
