### PR TITLE
added porstgresql start command to instructions

### PR DESCRIPTION
**Pull request by simonjamain**
added sudo `service postgresql start` so the `psql ` command doesn't fail afterwards

### CODE REVIEW

**Comment by sylvainbx** [comment]
Which distribution requires this?

**Comment by simonjamain** [comment]
I'm on Ubuntu 14.04.5 LTS (running on an c9.io workspace), postrgresql didn't seems to start automatically when I followed the instructions. I'm not a linux expert, so if this is usualy useless feel free to ignore it.

**Comment by simonjamain** [comment]
after a restart, the postgresql service is also down, it doesn't seems to launch automatically. I am digging into this

**Comment by simonjamain** [comment]
ok it looks like the issue is completely on my side

**Pull request closed without merging**
