### PR TITLE
English translation

### PR DESCRIPTION
**Pull request by lpgn**
I think I translated every thing or almost... might have missed something small. Have a issue cant find were to change the setting of calendar language.

### CODE REVIEW

**Comment by sylvainbx** [comment]
If you want to change the language of the datepicker widget, you simply need to replace, in [application.js](../tree/master/app/assets/javascripts/application.js#L23)

``` ruby
//= require angular-i18n/angular-locale_fr-fr.js
```

with the locale you want, picked from the [angular-i18n directory](../tree/master/vendor/assets/components/angular-i18n). 

Otherwise, I found strange that you change the € currency symbol by ¥. Maybe $ or £ would have been more appropriate for a hard-coded translation?

A last little detail: you put the name `XinFab` in some places of your pull request. We would prefer to keep the source code free from any trademarks on this project. So, please remove them for you pull request to be merged.

**Comment by lpgn** [comment]
Hi @sylvainbx its done with issues below but the site looks ok.

## Finished fixing:
- angular-locale_en-Us.js works.
- neutral translation
- currency symbol to $

## Can't find:
- summernote/lang/summernote-en-US
- select2/select2_locale_en
- moment/locale/en

**Comment by sylvainbx** [comment]
Ok, it was merged on branch [english](../tree/english).

@lpgn thanks for your contribution, this was much appreciated.

**Comment by lpgn** [comment]
no problem feel the same about your work!

**Comment by lpgn** [comment]
by the way still don't have a solution for:
- summernote/lang/summernote-en-US
- select2/select2_locale_en
- moment/locale/en

I tried to find on the directory and github it doesn't seams to have a english version of summernote.
Should I translate those as well?

**Pull request closed without merging**
